### ISSUE TITLE
Jasmine Tests in Typescript

### ISSUE THREAD

**Issue by stefanhuber** [ospatil/generator-node-typescript#8]
Is it possible to write the jasmine tests in typescript as well? Currently, only a javascript sample is given?

**Comment by ospatil** [comment]
It is certainly possible to write jasmine tests in TypeScript but will need a little plumbing. In current release it can be achieved as follows - 

1. Write tests in TypeScript in the _test_ directory. Follow the naming convention of `-spec.ts` suffix.
2. Add `test/**/*.ts` pattern as last entry in the _filesGlob_ section of the `tsconfig.json` so that the tests get compiled through the gulp _build_ task.
3. The compiled tests will go to _lib_ directory. This is certainly less that ideal but will work.
4. Change the gulp _test_ task to pick up tests from lib directory i.e. change `return gulp.src('test/*.js')` line to `return gulp.src('lib/*-spec.js')`.
5. Voila, tests running in TypeScript :).

Having said that, I personally find having tests in JavaScript really useful in two aspects -

1. It avoids the overhead of compiling tests along with code.
2. More importantly, it clarifies the client usage aspect. The consumers of a module written in TypeScript will not only be TypeScript but also JavaScript modules. The TypeScript usage is quite clear through the generated type definitions. Having tests in JavaScript clearly demonstrates how to use the module from JavaScript.

**Comment by stefanhuber** [comment]
Thank you very much!

These are very valid points you made about the JavaScript tests.

So far your generator was very helpful to me. I could use it in a university course, which I teach. It saved me really a lot of work. However, for students learning TypeScript it would be better to write also the tests in TypeScript!
